### ISSUE TITLE
1.0.0-release error on travel

### ISSUE THREAD

**Issue by Road-block** [Burserg/ZoneDetails#1]
` ZoneDetails\ZoneDetails-1.0.lua:702: attempt to index field '?' (a nil value)
ZoneDetails\ZoneDetails-1.0.lua:702: in function 'GetZoneDetails'
ZoneDetails\ZoneDetails-1.0.lua:529: in function 'RefreshAllData'
...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:76: in function 'OnMapChanged'
...ace\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:529: in function 'OnMapChanged'
...rface\Blizzard_WorldMap\Blizzard_WorldMap.lua:115: in function 'OnMapChanged'
...ace\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:37: in function 'SetMapID'`

Happens on crossing a loading screen I want to say? Not 100% sure.  
But I think it happened when I took the boat across continents.

**Comment by Burserg** [comment]
I'm trying to track down what caused this. Can you provide any further information?

- What boat were you on?
- What continent were you leaving?
- Did the error happen after the zone or prior to zone?

Anything you can give would be helpful. 1.0 was a big change with localization and I believe there are some zones that may be missing.

**Comment by Road-block** [comment]
Unfortunately I have a bug catching addon so I can easily copy paste the call-stack but a side-effect of that is I'm not getting a Lua error popup to the face the moment it happens.

I want to say it was taking boat from Menethil > Theramore, so moving between continents.
Should I revert or do you want me to stay on the 1.0.0 version so I can get more errors?

**Comment by Road-block** [comment]
`1x ZoneDetails\ZoneDetails-1.0.lua:658: attempt to index field '?' (a nil value)
ZoneDetails\ZoneDetails-1.0.lua:658: in function 'GetZoneDetails'
ZoneDetails\ZoneDetails-1.0.lua:529: in function 'RefreshAllData'
...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:76: in function 'OnMapChanged'
...ace\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:529: in function 'OnMapChanged'
...rface\Blizzard_WorldMap\Blizzard_WorldMap.lua:115: in function 'OnMapChanged'
...ace\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:37: in function 'SetMapID`
Tram loading screen from IF > Stormwind

**Comment by Burserg** [comment]
I went ahead and pulled 1.0 from the Twitch client. I'd revert to 0.9.4 until I have a bit of time to dig into why it broke. I'll likely be redoing some of the localization work that I had put in as it seems to be missing zone information and not refreshing on continent change.
